services/urls.py
from django.urls import path, include
from .views import accommodation_view as accommodation_views
from .views import hospital_view as hospital_views

app_name = 'services'

urlpatterns = [
    path('accommodations/', accommodation_views.AccommodationList.as_view(), name='accommodation_list_url'),
    path('accommodation/<int:pk>/', accommodation_views.AccommodationDetailView.as_view(), name='accommodation_detail_url'),
    path('room/<int:pk>/', accommodation_views.RoomDetailView.as_view(), name='room_details'),
    path('bookings/<int:user_id>/', accommodation_views.BookingsView.as_view(), name='bookings_url'),
    path('edit_booking/<int:booking_id>/', accommodation_views.BookingsView.as_view(), name='edit_booking_url'),
    path('print_invoice/<int:booking_id>/', accommodation_views.DownloadInvoice.as_view(), name='print_invoice_url'),
    path('make_accommodation_payment/<int:booking_id>/', accommodation_views.AccommodationPaymentView.as_view(), name='make_accommodation_payment_url'),
    path('delete_booking/<int:booking_id>/', accommodation_views.BookingDeleteView.as_view(), name='delete_booking_url'),


    path('hospitals/', hospital_views.HospitalList.as_view(), name='hospital_list_url'),
    path('hospital/<int:id>/', hospital_views.HospitalDetailsView.as_view(), name='hospital_details_url'),
    path('hospital/doctor/<int:doctor_id>', hospital_views.DoctorDetailsView.as_view(), name='doctor_details_url'),
    path('request_appointments/<int:doctor_id>/', hospital_views.DoctorDetailsView.as_view(), name='request_appointments_url'),
    path('my_appointments/<int:user_id>/', hospital_views.UserAppointmentView.as_view(), name='user_appointments_url'),
    path('edit_appointment/<int:appointment_id>/', hospital_views.UserAppointmentView.as_view(), name='edit_appointment_url'),
    path('delete_appointment/<int:appointment_id>/', hospital_views.DeleteAppointmentView.as_view(), name='delete_appointment_url'),

    # Doctor Controls
    path('manage-appointments/<int:doctor_id>/', hospital_views.ManageAppointmentsView.as_view(), name='manage_appointments_url'),
    path('approve-appointment/<int:approve_id>/', hospital_views.ManageAppointmentsView.as_view(), name='approve_appointmetn_url'),
    path('reject-appointment/<int:reject_id>/', hospital_views.ManageAppointmentsView.as_view(), name='reject_appointment_url'),
    path('release-appointment/<int:release_id>/', hospital_views.ManageAppointmentsView.as_view(), name='release_appointment_url'),
    path('download-appointment-invoice/<int:appointment_bill_id>/', hospital_views.DownloadAppointmentInvoice.as_view(), name='download_appointment_invoice'),
]

system/urls.py
from django.urls import path

urlpatterns = [

]

travel_aid/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users_auth.views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name='home_url'),
    path('admin/', admin.site.urls),
    path('auth/', include('users_auth.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('address/', include('address.urls')),
    path('service/', include('services.urls')),
    path('system/', include('system.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users_auth/urls.py
from django.urls import path, include
from . import views

app_name = 'authenticate'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login_url'),
    path('logout/', views.LogoutView.as_view(), name='logout_url'),
    path('profile/<int:pk>/', views.ProfileView.as_view(), name='profile_url'),
    path('register/', views.RegistrationView.as_view(), name='registration_url'),
    path('admin_dashboard/', views.AdminDashboardView.as_view(), name='admin_dashboard_url'),
    path('doctor_dashboard/<int:doctor_id>/', views.DoctorDashboardView.as_view(), name='doctor_dashboard_url'),
    path('police_dashboard/', views.PoliceDashboardView.as_view(), name='police_dashboard_url'),
    path('manager_dashboard/<int:manager_id>/', views.ManagerDashboardView.as_view(), name='manager_dashboard_url'),

    # Manager's Control
    path('add-accommodation/', views.AccommodationManageView.as_view(), name='add_accommodation'),
    path('edit-accommodation/<int:editable_id>',  views.AccommodationManageView.as_view(), name='edit_accommodation'),
    path('delete-accommodation/<int:deletable_id>', views.AccommodationManageView.as_view(), name='delete_accommodation'),

    path('add-room/', views.RoomManageView.as_view(), name='add_room_url'),
    path('edit-room/<int:editable_id>', views.RoomManageView.as_view(), name='edit_room_url'),
    path('delete-room/<int:deletable_id>', views.RoomManageView.as_view(), name='delete_room_url'),

    path('manage-booking-request/<int:manager_id>', views.ManageBookingRequestView.as_view(), name='manage_booking_request'),
    path('approve-booking-request/<int:approvable_id>', views.ManageBookingRequestView.as_view(), name='approve_booking_request'),
    path('reject-booking-request/<int:rejectable_id>', views.ManageBookingRequestView.as_view(), name='reject_booking_request'),

    # managing user message
    path('send-message/', views.ManageUserMessage.as_view(), name='send_message')
]

services/models/accommodation_models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from address.models import Address
# Create your models here.
from users_auth.models import APPROVE_USER_STATUS, User

AVAILABLE = 1
PENDING = 2
BOOKED = 3

AC = 1
Non_AC = 2

BKASH = 1
ROCKET = 2

ROOM_STATUS_CHOICES = (
    (AVAILABLE, "Available"),
    (PENDING, "Pending"),
    (BOOKED, "Booked")
)

ROOM_TYPE_CHOICES = (
    ('AC', 'AC'),
    ('Non AC', 'Non AC')
)

PAYMENT_PROVIDERS = (
    (BKASH, "bKash"),
    (ROCKET, "Rocket"),
)

PAYMENT_STATUS_CHOICES = (
    ('Paid', 'Paid'),
    ('Unpaid', 'Unpaid'),
    ('Partially Paid', 'Partially Paid'),
    ('Over Paid', 'Over Paid'),
)


class Accommodation(models.Model):
    name = models.CharField(max_length=200)
    owner = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='home_owner', null=True, blank=True)
    image = models.ImageField(upload_to='accommodations', null=True, blank=True)
    address = models.ForeignKey(Address, on_delete=models.DO_NOTHING, related_name='accommodation_address' , null=True, blank=True)
    description = RichTextUploadingField(null=True, blank=True)

    def __str__(self):
        return self.name


class Room(models.Model):
    accommodation = models.ForeignKey(Accommodation, on_delete=models.SET_NULL, null=True, blank=True)
    room_number = models.CharField(max_length=100)
    image = models.ImageField(upload_to='rooms', null=True, blank=True)
    description = RichTextUploadingField(null=True, blank=True)
    cost_per_day = models.FloatField(default=0)
    room_type = models.CharField(choices=ROOM_TYPE_CHOICES, default='Non AC', max_length=20)
    current_status = models.IntegerField(choices=ROOM_STATUS_CHOICES, default=1)

    def __str__(self):
        return "{a} -> {b}".format(a=self.room_number, b=self.accommodation.name)


class BookAccommodation(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='book_user', null=True, blank=True)
    room = models.ForeignKey(Room, on_delete=models.SET_NULL, related_name='book_room', null=True, blank=True)
    start_date = models.DateField()
    end_date = models.DateField()
    requested_date = models.DateTimeField(auto_now_add=True)
    total_bills = models.FloatField()
    paid_bills = models.FloatField(default=0)
    due_bills = models.FloatField(default=0)
    payment_status = models.CharField(choices=PAYMENT_STATUS_CHOICES, default="Unpaid", max_length=20)
    status = models.IntegerField(choices=APPROVE_USER_STATUS, default=1)
    user_note = models.TextField(null=True, blank=True)
    manager_note = models.TextField(null=True, blank=True)

    def __str__(self):
        return "{a} by {b} ".format(a=self.room.room_number, b=self.user.first_name)


class AccommodationBillPayment(models.Model):
    bill = models.ForeignKey(BookAccommodation, on_delete=models.SET_NULL, related_name='bill', null=True, blank=True)
    payment_bdt = models.FloatField()
    payment_provider = models.IntegerField(choices=PAYMENT_PROVIDERS, default=1)
    account_number = models.CharField(max_length=11, null=True, blank=True)
    transaction_id = models.CharField(max_length=20, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    note = models.TextField(null=True, blank=True)
    proof = models.FileField(upload_to='payments/', null=True, blank=True)

    def __str__(self):
        return "Bill of - {a}".format(a=self.bill.room.room_number)

templates/modals/add_accommodation.html
<!-- Modal -->
<div class="modal fade" id="addAccommodation" role="dialog">
<form action="{% url 'authenticate:add_accommodation' %}" method="post" enctype="multipart/form-data"> {% csrf_token %}
    <div class="modal-dialog modal-lg">

      <!-- Modal content-->
      <div class="modal-content">

        <div class="modal-header">
          <h4 class="modal-title">Add Your Accommodation</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        <div class="modal-body">

                <div class="row">
                    <div class="col-md-8">
                        <label for="name" class="form-check-label">Name<span style="font-size: 14px; font-weight: bold;" id="error_msg" class="text-danger"></span> </label>
                        <input type="text" id="name" name="name" class="form-control" required>
                    </div>
                    <div class="col-md-4">
                        <label for="image" class="form-check-label">Image</label>
                        <input type="file" id="image" name="image" class="form-control" required>
                    </div>
                </div>
                <div class="row my-3" id='address'>
                    <div class="col-md-12">
                        <label class="form-check-label">Address <span style="font-size: 14px; font-weight: bold;" id="error_msg2" class="text-danger"></span> </label>
                        <div class="row">
                            <div class="col-md-4">
                                <input type="text" id="location" name="location" class="form-control" placeholder="Location" required>
                            </div>
                            <div class="col-md-4">
                                <select name="district" id="district" class="form-control" required>
                                    <option disabled selected>District</option>
                                {% for district in districts %}
                                    <option value="{{ district.id }}">{{ district.name }}</option>
                                {% endfor %}
                                </select>
                            </div>
                            <div class="col-md-4">
                                <input type="text" id="zip_code" name="zip_code" class="form-control" placeholder="Zip Code" required>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col-md-12">
                        <label for="description" class="form-check-label">Description<span style="font-size: 14px; font-weight: bold;" id="error_msg2" class="text-danger"></span> </label>
                        <textarea id="description" maxlength="2000" name="description" rows="50"
                                          data-processed="0"
                                          data-config='{"skin": "moono-lisa", "toolbar_Basic":
                              [["Source", "-", "Bold", "Italic", "Image"]],
                               "toolbar_Full": [["Styles", "Format", "Bold", "Italic", "Underline",
                                "Strike", "SpellChecker", "Undo", "Redo"], ["Link", "Unlink", "Anchor"],
                                ["Image", "Flash", "Table", "HorizontalRule"], ["TextColor", "BGColor"],
                                ["Smiley", "SpecialChar"], ["Source"],  ["JustifyLeft", "JustifyCenter", "JustifyRight", "JustifyBlock"], ["Outdent", "Indent"]],
                                "toolbar": "Full", "height": 200, "filebrowserWindowWidth": 940,

                                "filebrowserWindowHeight": 725,
                                "filebrowserUploadUrl": "/ckeditor/upload/",
                                "filebrowserBrowseUrl": "/ckeditor/browse/",

                                "language": "en-us" }'
                                          data-external-plugin-resources='[]'
                                          data-type="ckeditortype" required>

                             </textarea>
                    </div>
                </div>

        </div>
        <div class="modal-footer">
          <button type="submit" id="add_btn" class="btn btn-success">Add</button>
          <button type="button" class="btn btn-info" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>

</form>
</div>

templates/modals/approve_appointment.html
<!-- Modal -->
<div class="modal fade" id="approveAppointment{{ appointment.id }}" role="dialog">
<form action="{% url 'services:approve_appointmetn_url' appointment.id %}" method="post"> {% csrf_token %}
    <div class="modal-dialog modal-lg">

      <!-- Modal content-->
      <div class="modal-content">

        <div class="modal-header">
          <h4 class="modal-title">Approve Appointment</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        <div class="modal-body">
            <div class="row my-3">
                    <div class="col-md-12">
                        <label for="doctors_note" class="form-check-label">Doctor's Note<span style="font-size: 14px; font-weight: bold;" id="error_msg2" class="text-danger"></span> </label>
                        <textarea id="doctors_note{{ appointment.id }}" maxlength="2000" name="doctors_note" rows="50"
                                          data-processed="0"
                                          data-config='{"skin": "moono-lisa", "toolbar_Basic":
                              [["Source", "-", "Bold", "Italic", "Image"]],
                               "toolbar_Full": [["Styles", "Format", "Bold", "Italic", "Underline",
                                "Strike", "SpellChecker", "Undo", "Redo"], ["Link", "Unlink", "Anchor"],
                                ["Image", "Flash", "Table", "HorizontalRule"], ["TextColor", "BGColor"],
                                ["Smiley", "SpecialChar"], ["Source"],  ["JustifyLeft", "JustifyCenter", "JustifyRight", "JustifyBlock"], ["Outdent", "Indent"]],
                                "toolbar": "Full", "height": 200, "filebrowserWindowWidth": 940,

                                "filebrowserWindowHeight": 725,
                                "filebrowserUploadUrl": "/ckeditor/upload/",
                                "filebrowserBrowseUrl": "/ckeditor/browse/",

                                "language": "en-us" }'
                                          data-external-plugin-resources='[]'
                                          data-type="ckeditortype">

                             </textarea>
                    </div>
                </div>
        </div>
        <div class="modal-footer">
          <button type="submit" id="approve_appointment_btn{{ appointment.id }}" class="btn btn-success">Approve</button>
          <button type="button" class="btn btn-info" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>

</form>
</div>

templates/modals/approve_booking.html
<!-- Modal -->
<div class="modal fade" id="approveBooking{{ booking.id }}" role="dialog">
<form action="{% url 'authenticate:approve_booking_request' booking.id %}" method="post"> {% csrf_token %}
    <div class="modal-dialog modal-lg">

      <!-- Modal content-->
      <div class="modal-content">

        <div class="modal-header">
          <h4 class="modal-title">Approve Appointment</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        <div class="modal-body">
            <div class="row my-3">
                <div class="col-md-12">
                    <label for="start_date" class="form-check-label">Note (Optional)</label>
                    <textarea name="note" class="form-control" id="manager_note{{ booking.id }}" cols="30" rows="5"></textarea>
                </div>
            </div>
        </div>
        <div class="modal-footer">
          <button type="submit" id="approve_booking_btn{{ booking.id }}" class="btn btn-success">Approve</button>
          <button type="button" class="btn btn-info" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>

</form>
</div>

templates/modals/book_room_modal.html
<!-- Modal -->
<div class="modal fade" id="bookRoom{{ room.id }}" role="dialog">
<form action="{% url 'services:room_details' room.id %}" method="post"> {% csrf_token %}
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">

        <div class="modal-header">
          <h4 class="modal-title">Choose Date Range</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        <div class="modal-body">

                <div class="row">
                    <div class="col-md-9">
                        <label for="start_date" class="form-check-label">From Date <span style="font-size: 14px; font-weight: bold;" id="error_msg" class="text-danger"></span> </label>
                        <input type="text" id="from_date" name="from_date" class="form-control" required>
                    </div>
                </div>
                <div class="row my-3" id='to_date_div'>
                    <div class="col-md-9">
                        <label for="to_date" class="form-check-label">To Date <span style="font-size: 14px; font-weight: bold;" id="error_msg2" class="text-danger"></span> </label>
                        <input type="text" id="to_date" name="to_date" class="form-control" required>
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col-md-6">
                        <label for="total_bills" class="form-check-label">Total Cost(BDT)</label>
                        <input readonly type="text" id="total_bills" name="total_bills" class="form-control">
                    </div>
                </div>
            <div class="row">
                    <div class="col-md-12">
                        <label for="start_date" class="form-check-label">Note (Optional)</label>
                        <textarea name="note" class="form-control" id="note" cols="30" rows="5"></textarea>
                    </div>
                </div>
        </div>
        <div class="modal-footer">
          <button type="submit" id="request_btn" class="btn btn-success">Request</button>
          <button type="button" class="btn btn-info" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>

</form>
</div>

templates/modals/delete_appointment.html
<!-- Modal -->
<div class="modal fade" id="delete_appointment{{ appointment.id }}" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">

        <div class="modal-header">
          <h6 class="modal-title">Are You Sure to Delete the Following Appointment?</h6>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        <div class="modal-body">
           <p class="lead">Appointment Request to Doctor : {{ appointment.doctor.get_full_name }} </p>
        </div>
        <div class="modal-footer">
            <a href="{% url 'services:delete_appointment_url' appointment.id %}" class="btn btn-danger">Delete</a>
          <button type="button" class="btn btn-info" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>

</div>

templates/modals/edit_appointment.html
<!-- Modal -->
<div class="modal fade" id="editAppointment{{ appointment.id }}" role="dialog">
<form action="{% url 'services:edit_appointment_url' appointment.id %}" method="post"> {% csrf_token %}
    <div class="modal-dialog modal-lg">

      <!-- Modal content-->
      <div class="modal-content">

        <div class="modal-header">
          <h4 class="modal-title">Update Appointment Form</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        <div class="modal-body">

                <div class="row">
                    <div class="col-md-6">
                        <label for="appointment_date" class="form-check-label">Appointment Date <span style="font-size: 14px; font-weight: bold;" id="error_msg" class="text-danger"></span> </label>
                        <input type="text" id="appointment_date" value="{{ appointment.date | date:"b d, Y h:i A" }}" name="appointment_date" class="form-control" required>
                    </div>
                </div>
                <div class="row my-3" id='to_date_div'>
                    <div class="col-md-12">
                        <label for="problem_desc" class="form-check-label">Problem Description <span style="font-size: 14px; font-weight: bold;" id="error_msg2" class="text-danger"></span> </label>
                        <textarea id="problem_desc{{ appointment.id }}" maxlength="2000" name="problem_desc" rows="50"
                                          data-processed="0"
                                          data-config='{"skin": "moono-lisa", "toolbar_Basic":
                              [["Source", "-", "Bold", "Italic", "Image"]],
                               "toolbar_Full": [["Styles", "Format", "Bold", "Italic", "Underline",
                                "Strike", "SpellChecker", "Undo", "Redo"], ["Link", "Unlink", "Anchor"],
                                ["Image", "Flash", "Table", "HorizontalRule"], ["TextColor", "BGColor"],
                                ["Smiley", "SpecialChar"], ["Source"],  ["JustifyLeft", "JustifyCenter", "JustifyRight", "JustifyBlock"], ["Outdent", "Indent"]],
                                "toolbar": "Full", "height": 200, "filebrowserWindowWidth": 940,

                                "filebrowserWindowHeight": 725,
                                "filebrowserUploadUrl": "/ckeditor/upload/",
                                "filebrowserBrowseUrl": "/ckeditor/browse/",

                                "language": "en-us" }'
                                          data-external-plugin-resources='[]'
                                          data-type="ckeditortype"> {{ appointment.description }}

                             </textarea>
                    </div>
                </div>
        </div>
        <div class="modal-footer">
          <button type="submit" id="update_appointment_btn" class="btn btn-success">Request</button>
          <button type="button" class="btn btn-info" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>

</form>
</div>

templates/modals/edit_room.html
<!-- Modal -->
<div class="modal fade" id="editRoom{{ room.id }}" role="dialog">
<form action="{% url 'authenticate:edit_room_url' room.id %}" method="post" enctype="multipart/form-data"> {% csrf_token %}
    <div class="modal-dialog modal-lg">

      <!-- Modal content-->
      <div class="modal-content">

        <div class="modal-header">
          <h4 class="modal-title">Update Room</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        <div class="modal-body">

                <div class="row">
                    <div class="col-md-6">
                        <label for="room_number{{ room.id }}" class="form-check-label">Room Number </label>
                        <input type="text" id="room_number{{ room.id }}" value="{{ room.room_number }}" name="room_number" class="form-control" required>
                    </div>
                    <div class="col-md-6">
                        <label class="form-check-label">Belongs To</label>
                        <select name="accommodation" id="accommodation{{ room.id }}" class="form-control">
                            {% for accommodation in accommodations %}
                                <option value="{{ accommodation.id }}" {% ifequal room.accommodation accommodation %}
                                    selected
                                 {% endifequal %}>{{ accommodation.name }}</option>
                            {% endfor %}
                        </select>
                    </div>

                </div>

                <div class="row mb-3">
                    <div class="col-md-12">
                        <label for="room_description" class="form-check-label">Description<span style="font-size: 14px; font-weight: bold;" id="error_msg2" class="text-danger"></span> </label>
                        <textarea id="room_description{{ room.id }}" maxlength="2000" name="room_description" rows="50"
                                          data-processed="0"
                                          data-config='{"skin": "moono-lisa", "toolbar_Basic":
                              [["Source", "-", "Bold", "Italic", "Image"]],
                               "toolbar_Full": [["Styles", "Format", "Bold", "Italic", "Underline",
                                "Strike", "SpellChecker", "Undo", "Redo"], ["Link", "Unlink", "Anchor"],
                                ["Image", "Flash", "Table", "HorizontalRule"], ["TextColor", "BGColor"],
                                ["Smiley", "SpecialChar"], ["Source"],  ["JustifyLeft", "JustifyCenter", "JustifyRight", "JustifyBlock"], ["Outdent", "Indent"]],
                                "toolbar": "Full", "height": 200, "filebrowserWindowWidth": 940,

                                "filebrowserWindowHeight": 725,
                                "filebrowserUploadUrl": "/ckeditor/upload/",
                                "filebrowserBrowseUrl": "/ckeditor/browse/",

                                "language": "en-us" }'
                                          data-external-plugin-resources='[]'
                                          data-type="ckeditortype" required> {{ room.description }}

                             </textarea>
                    </div>
                </div>

                <div class="row">
                <div class="col-md-4">
                        <label for="room_image{{ room.id }}e" class="form-check-label">Image</label>
                        <input type="file" id="room_image{{ room.id }}" name="room_image" class="form-control">
                    </div>

                    <div class="col-md-4">
                        <label for="room_type{{ room.id }}" class="form-check-label">Select Room Type</label>
                        <select name="room_type" id="room_type{{ room.id }}" class="form-control">
                            {% for type in room_type %}
                                <option value="{{ type.0 }}" {% ifequal type.0 room.room_type %}
                                    selected
                                {% endifequal %}
                                >{{ type.1 }}</option>
                            {% endfor %}
                        </select>

                    </div>
                     <div class="col-md-4">
                         <label for="cost_per_day{{ room.id }}" class="form-check-label">Cost Per Day</label>
                        <input type="text" id="cost_per_day{{ room.id }}" value="{{ room.cost_per_day }}" name="cost_per_day" class="form-control numberField" required>
                    </div>

                </div>

        </div>
        <div class="modal-footer">
          <button type="submit" id="room_update_btn" class="btn btn-success">Add</button>
          <button type="button" class="btn btn-info" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>

</form>
</div>

templates/modals/payment_history.html
<!-- Modal -->
<div class="modal fade" id="paymentHistory{{ booking.id }}" role="dialog">
<form action="" method="post"> {% csrf_token %}
    <div class="modal-dialog modal-lg">

      <!-- Modal content-->
      <div class="modal-content">

        <div class="modal-header">
          <h4 class="modal-title">Payment History</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        <div class="modal-body">

            <table class="table table-stripped">
                <thead>
                    <tr>
                      <th scope="col">#</th>
                      <th scope="col">Amount Sent</th>
                      <th scope="col">Payment Provider</th>
                      <th scope="col">From</th>
                      <th scope="col">To</th>
                      <th scope="col">TXID</th>
                      <th scope="col"> Proof</th>
                    </tr>
              </thead>
              <tbody>

                 {% for payment in booking.bill.all %}

                  <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ payment.payment_bdt }}</td>
                    <td>{{ payment.get_payment_provider_display }}</td>
                    <td>{{ payment.account_number }}</td>
                    <td>{{ request.user.user_info.cell }}</td>
                    <td>{{ payment.transaction_id }}</td>
                    <td><a href="{{ payment.proof.url  }}" download>Download</a></td>
                  </tr>

                {% endfor %}

              </tbody>
          </table>

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-info" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>

</form>
</div>

templates/modals/reject_booking.html
<!-- Modal -->
<div class="modal fade" id="rejectBooking{{ booking.id }}" role="dialog">
<form action="{% url 'authenticate:reject_booking_request' booking.id %}" method="post"> {% csrf_token %}
    <div class="modal-dialog modal-lg">

      <!-- Modal content-->
      <div class="modal-content">

        <div class="modal-header">
          <h4 class="modal-title">Reject Appointment</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        <div class="modal-body">
            <div class="row my-3">
                <div class="col-md-12">
                    <label for="start_date" class="form-check-label">Note (Required)</label>
                    <textarea name="note" class="form-control" id="manager_note{{ booking.id }}" cols="30" rows="5" required></textarea>
                </div>
            </div>
        </div>
        <div class="modal-footer">
          <button type="submit" id="approve_booking_btn{{ booking.id }}" class="btn btn-danger">Reject</button>
          <button type="button" class="btn btn-info" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>

</form>
</div>