services/urls.py
from django.urls import path, include
from .views import accommodation_view as accommodation_views
from .views import hospital_view as hospital_views

app_name = 'services'

urlpatterns = [
    path('accommodations/', accommodation_views.AccommodationList.as_view(), name='accommodation_list_url'),
    path('accommodation/<int:pk>/', accommodation_views.AccommodationDetailView.as_view(), name='accommodation_detail_url'),
    path('room/<int:pk>/', accommodation_views.RoomDetailView.as_view(), name='room_details'),
    path('bookings/<int:user_id>/', accommodation_views.BookingsView.as_view(), name='bookings_url'),
    path('edit_booking/<int:booking_id>/', accommodation_views.BookingsView.as_view(), name='edit_booking_url'),
    path('print_invoice/<int:booking_id>/', accommodation_views.DownloadInvoice.as_view(), name='print_invoice_url'),
    path('make_accommodation_payment/<int:booking_id>/', accommodation_views.AccommodationPaymentView.as_view(), name='make_accommodation_payment_url'),
    path('delete_booking/<int:booking_id>/', accommodation_views.BookingDeleteView.as_view(), name='delete_booking_url'),


    path('hospitals/', hospital_views.HospitalList.as_view(), name='hospital_list_url'),
    path('hospital/<int:id>/', hospital_views.HospitalDetailsView.as_view(), name='hospital_details_url'),
    path('hospital/doctor/<int:doctor_id>', hospital_views.DoctorDetailsView.as_view(), name='doctor_details_url'),
    path('request_appointments/<int:doctor_id>/', hospital_views.DoctorDetailsView.as_view(), name='request_appointments_url'),
    path('my_appointments/<int:user_id>/', hospital_views.UserAppointmentView.as_view(), name='user_appointments_url'),
    path('edit_appointment/<int:appointment_id>/', hospital_views.UserAppointmentView.as_view(), name='edit_appointment_url'),
    path('delete_appointment/<int:appointment_id>/', hospital_views.DeleteAppointmentView.as_view(), name='delete_appointment_url'),

    # Doctor Controls
    path('manage-appointments/<int:doctor_id>/', hospital_views.ManageAppointmentsView.as_view(), name='manage_appointments_url'),
    path('approve-appointment/<int:approve_id>/', hospital_views.ManageAppointmentsView.as_view(), name='approve_appointmetn_url'),
    path('reject-appointment/<int:reject_id>/', hospital_views.ManageAppointmentsView.as_view(), name='reject_appointment_url'),
    path('release-appointment/<int:release_id>/', hospital_views.ManageAppointmentsView.as_view(), name='release_appointment_url'),
    path('download-appointment-invoice/<int:appointment_bill_id>/', hospital_views.DownloadAppointmentInvoice.as_view(), name='download_appointment_invoice'),
]

system/urls.py
from django.urls import path

urlpatterns = [

]

travel_aid/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users_auth.views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name='home_url'),
    path('admin/', admin.site.urls),
    path('auth/', include('users_auth.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('address/', include('address.urls')),
    path('service/', include('services.urls')),
    path('system/', include('system.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users_auth/urls.py
from django.urls import path, include
from . import views

app_name = 'authenticate'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login_url'),
    path('logout/', views.LogoutView.as_view(), name='logout_url'),
    path('profile/<int:pk>/', views.ProfileView.as_view(), name='profile_url'),
    path('register/', views.RegistrationView.as_view(), name='registration_url'),
    path('admin_dashboard/', views.AdminDashboardView.as_view(), name='admin_dashboard_url'),
    path('doctor_dashboard/<int:doctor_id>/', views.DoctorDashboardView.as_view(), name='doctor_dashboard_url'),
    path('police_dashboard/', views.PoliceDashboardView.as_view(), name='police_dashboard_url'),
    path('manager_dashboard/<int:manager_id>/', views.ManagerDashboardView.as_view(), name='manager_dashboard_url'),

    # Manager's Control
    path('add-accommodation/', views.AccommodationManageView.as_view(), name='add_accommodation'),
    path('edit-accommodation/<int:editable_id>',  views.AccommodationManageView.as_view(), name='edit_accommodation'),
    path('delete-accommodation/<int:deletable_id>', views.AccommodationManageView.as_view(), name='delete_accommodation'),

    path('add-room/', views.RoomManageView.as_view(), name='add_room_url'),
    path('edit-room/<int:editable_id>', views.RoomManageView.as_view(), name='edit_room_url'),
    path('delete-room/<int:deletable_id>', views.RoomManageView.as_view(), name='delete_room_url'),

    path('manage-booking-request/<int:manager_id>', views.ManageBookingRequestView.as_view(), name='manage_booking_request'),
    path('approve-booking-request/<int:approvable_id>', views.ManageBookingRequestView.as_view(), name='approve_booking_request'),
    path('reject-booking-request/<int:rejectable_id>', views.ManageBookingRequestView.as_view(), name='reject_booking_request'),

    # managing user message
    path('send-message/', views.ManageUserMessage.as_view(), name='send_message')
]

templates/doctor_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  <script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
  <script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
  <link rel="stylesheet" href="{% static 'fa/css/font-awesome.css' %}">


  <style media="screen">
    a:link {
      text-decoration: none;
    }

    a {
      color: white;
    }

    a:hover {
      color: white;
    }




    /*---------------------------------------
       Social section
    -----------------------------------------*/
    footer {
      padding: 0px 0px 0px 0px;
      background-color: black;
      margin: 0px;
    }


    #ftr {

      padding: 20px;
    }

    .fa {

      font-size: 23px;
      width:25px;
      text-align: center;
      text-decoration: none;
      margin: 5px 2px;
      border-radius: 50%;
    }

    .fa:hover {
      opacity: 0.5;
      text-decoration: none;
    }

    .fa-facebook {
      background: #3B5998;
      color: white;
      margin-top: 30px;
    }

    .fa-whatsapp {
      background: #25d366;
      color: white;
    }

    .fa-twitter {
      background: #55ACEE;
      color: white;
    }

    .fa-instagram {
      background: #125688;
      color: white;
    }

    p {
      text-align: center;

    }





    body {

      padding-left: 240px;
    }
    main {
      position: relative;
      height: 100vh;
    }

    .menu {
      background: #5bc995;
      height: 100vh;
      width: 240px;
      position: fixed;
      top: 0px;
      left: 0;
      z-index: 5;
      outline: none;
    }
    .menu .avatar {
      background: rgba(0, 0, 0, 0.1);
      padding: 2em 0.5em;
      text-align: center;
    }
    .menu .avatar img {
      width: 100px;
      border-radius: 50%;
      overflow: hidden;
      border: 4px solid #ffea92;
      box-shadow: 0 0 0 4px rgba(255, 255, 255, 0.2);
    }
    .menu .avatar h2 {
      font-weight: normal;
      margin-bottom: 0;
    }
    .menu ul {
      list-style: none;
      padding: 0.5em 0;
      margin: 0;
    }
    .menu ul li {
      padding: 0.5em 1em 0.5em 3em;
      font-size: 0.95em;
      font-weight: regular;
      background-repeat: no-repeat;
      background-position: left 15px center;
      background-size: auto 20px;
      transition: all 0.15s linear;
      cursor: pointer;
    }
    .menu ul li.icon-dashboard {
      background-image: url("http://www.entypo.com/images//gauge.svg");
    }
    .menu ul li.icon-customers {
      background-image: url("http://www.entypo.com/images//briefcase.svg");
    }
    .menu ul li.icon-users {
      background-image: url("http://www.entypo.com/images//users.svg");
    }
    .menu ul li.icon-calendar {
      background-image: url("http://www.entypo.com/images//calendar.svg");
    }

    .menu ul li:hover {
      background-color: rgba(0, 0, 0, 0.1);
    }
    .menu ul li:focus {
      outline: none;
    }
    @media screen and (max-width: 900px) and (min-width: 400px) {
      body {
        padding-left: 90px;
      }
      .menu {
        width: 90px;
      }
      .menu .avatar {
        padding: 0.5em;
        position: relative;
      }
      .menu .avatar img {
        width: 60px;
      }
      .menu .avatar h2 {
        opacity: 0;
        position: absolute;
        top: 50%;
        left: 100px;
        margin: 0;
        min-width: 200px;
        border-radius: 4px;
        background: rgba(0, 0, 0, 0.4);
        transform: translate3d(-20px, -50%, 0);
        transition: all 0.15s ease-in-out;
      }
      .menu .avatar:hover h2 {
        opacity: 1;
        transform: translate3d(0px, -50%, 0);
      }
      .menu ul li {
        height: 60px;
        background-position: center center;
        background-size: 30px auto;
        position: relative;
      }
      .menu ul li span {
        opacity: 0;
        position: absolute;
        background: rgba(0, 0, 0, 0.5);
        padding: 0.2em 0.5em;
        border-radius: 4px;
        top: 50%;
        left: 80px;
        transform: translate3d(-15px, -50%, 0);
        transition: all 0.15s ease-in-out;
      }
      .menu ul li span:before {
        content: '';
        width: 0;
        height: 0;
        position: absolute;
        top: 50%;
        left: -5px;
        border-top: 5px solid transparent;
        border-bottom: 5px solid transparent;
        border-right: 5px solid rgba(0, 0, 0, 0.5);
        transform: translateY(-50%);
      }
      .menu ul li:hover span {
        opacity: 1;
        transform: translate3d(0px, -50%, 0);
      }
    }
    @media screen and (max-width: 400px) {
      body {
        padding-left: 0;
      }
      .menu {
        width: 230px;
        box-shadow: 0 0 0 100em rgba(0, 0, 0, 0);
        transform: translate3d(-230px, 0, 0);
        transition: all 0.3s ease-in-out;
      }
      .menu .smartphone-menu-trigger {
        width: 40px;
        height: 40px;
        position: absolute;
        left: 100%;
        background: #5bc995;
      }
      .menu .smartphone-menu-trigger:before,
      .menu .smartphone-menu-trigger:after {
        content: '';
        width: 50%;
        height: 2px;
        background: #fff;
        border-radius: 10px;
        position: absolute;
        top: 45%;
        left: 50%;
        transform: translate3d(-50%, -50%, 0);
      }
      .menu .smartphone-menu-trigger:after {
        top: 55%;
        transform: translate3d(-50%, -50%, 0);
      }
      .menu ul li {
        padding: 1em 1em 1em 3em;
        font-size: 1.2em;
      }
      .menu:focus {
        transform: translate3d(0, 0, 0);
        box-shadow: 0 0 0 100em rgba(0, 0, 0, 0.6);
      }
      .menu:focus .smartphone-menu-trigger {
        pointer-events: none;
      }
    }

  </style>
    {% block style %}
    {% endblock %}
</head>

<body>
  <!-- partial:index.partial.html -->
  <nav class="menu" tabindex="0">
    <div class="smartphone-menu-trigger"></div>
    <header class="avatar">
      <img src="{{ request.user.user_info.profile_picture.url }}" alt="Profile Pic" />
      <br><br>

      <h3 class="font-weight-bold"><a href="{% url 'authenticate:profile_url' request.user.id %}">{{ request.user.get_full_name }}</a></h3>
    </header>
    <ul>
      <li tabindex="0" class="icon-dashboard"> <a style="color:white; text-decoration:none;" href="{% url 'authenticate:doctor_dashboard_url' request.user.id %}"><span>Dashboard</span></a> </li>
      <li tabindex="0" class="icon-calendar"> <a style="color:white; text-decoration:none;" href="{% url 'services:manage_appointments_url' request.user.id %}"><span>Manage Appointments</span></a></li>
      <li tabindex="0" class="fa fa-sign-out"><a href="{% url 'authenticate:logout_url' %}" style="color:white; text-decoration: none"><span>Logout</span></a></li>
    </ul>
  </nav>
  <main>
    <br><br>
    <!-- content start-->
    {% block content %}
    {% endblock content %}
    <!-- content end-->


    <br><br><br><br><br><br><br>

  </main>
  <!-- partial -->
<script src="{% static 'fa/js/fontawesome.js' %}"></script>
{% block script %}

{% endblock %}
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    {% include 'navbar.html' %}

        {% if messages  %}
              {% for message in messages  %}
                <h5 class="font-weight-bold text-center alert alert-{{message.tags}}"> {{message}} </h5>
              {% endfor %}
        {% endif %}

    {% include 'slider.html' %}

    <section class="m-5" id="Services" style="background: #e4dde9">
		<div class="row">
			<div class="col-lg-12 my-3">
				<h2 class="text-center">Select Your Service</h2>
			</div>
		</div>
		<div class="row mx-3">
			<div class="col-lg-6">
				<div class="card mb-3">
					<div class="card-header">
						<h3 class="text-center">Accommodations</h3>
					</div>
					<div class="card-body">
						<img style="height: 240px; width: 830px;" src="{% static 'img/sliders/accommodation1.jpg' %}" alt="" class="img-fluid">
					</div>
					<div class="card-footer">
						<a href="{% url 'services:accommodation_list_url' %}" type="button" class="btn btn-primary btn-block">Search Accommodation</a>
					</div>
				</div>
			</div>
			<div class="col-lg-6">
				<div class="card mb-3">
					<div class="card-header">
						<h3 class="text-center">Hospital</h3>
					</div>
					<div class="card-body">
						<img style="height: 240px; width: 830px;" src="{% static 'img/sliders/hospital2.jpg' %}" alt="" class="img-fluid">
					</div>
					<div class="card-footer">
						<a href="{% url 'services:hospital_list_url' %}" type="button" class="btn btn-primary btn-block">Search Hospital</a>
					</div>
				</div>
			</div>
		</div>
	</section>

    <section class="m-5 jumbotron">
        <!--Section heading-->
        <h2 class="h1-responsive font-weight-bold text-center my-4">Contact us</h2>
        <!--Section description-->
        <p class="text-center w-responsive mx-auto mb-5">Do you have any questions? Please do not hesitate to contact us directly. Our team will come back to you within
            a matter of hours to help you.</p>

        <div class="row">

                <div class="col-md-2">
                </div>

                <div class="col-md-8">
                    <form class="form from-group" method="post" action="{% url 'authenticate:send_message' %}">
                        {% csrf_token %}
                        {% if user.is_authenticated %}
                            <textarea id="message" maxlength="2000" name="message" rows="50"
                                          data-processed="0"
                                          data-config='{"skin": "moono-lisa", "toolbar_Basic":
                              [["Source", "-", "Bold", "Italic", "Image"]],
                               "toolbar_Full": [["Styles", "Format", "Bold", "Italic", "Underline",
                                "Strike", "SpellChecker", "Undo", "Redo"], ["Link", "Unlink", "Anchor"],
                                ["Image", "Flash", "Table", "HorizontalRule"], ["TextColor", "BGColor"],
                                ["Smiley", "SpecialChar"], ["Source"],  ["JustifyLeft", "JustifyCenter", "JustifyRight", "JustifyBlock"], ["Outdent", "Indent"]],
                                "toolbar": "Full", "height": 200, "filebrowserWindowWidth": 940,

                                "filebrowserWindowHeight": 725,
                                "filebrowserUploadUrl": "/ckeditor/upload/",
                                "filebrowserBrowseUrl": "/ckeditor/browse/",

                                "language": "en-us" }'
                                          data-external-plugin-resources='[]'
                                          data-type="ckeditortype">

                             </textarea>

                            <input class="btn btn-outline btn-info mt-3" type="submit" name="" value="Send">
                        {% else %}

                            <h2 class="text-info text-center"> Please Log In to reach us. </h2>

                        {% endif %}


                    </form>
                </div>

                    <div class="col-md-2">
                    </div>


        </div>

    </section>


{% endblock content %}

{% block script %}
    <!-- This Script is required for Carousel Animaiton -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <script>
        $(document).ready(function (){
           $("#clickMe").click(function (){
               alert("Hi there. ");
           }) ;
        });
    </script>

{% endblock %}

templates/manager_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  <script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
  <script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
  <link rel="stylesheet" href="{% static 'fa/css/font-awesome.css' %}">


  <style media="screen">
    a:link {
      text-decoration: none;
    }

    a {
      color: white;
    }

    a:hover {
      color: white;
    }




    /*---------------------------------------
       Social section
    -----------------------------------------*/
    footer {
      padding: 0px 0px 0px 0px;
      background-color: black;
      margin: 0px;
    }


    #ftr {

      padding: 20px;
    }

    .fa {

      font-size: 23px;
      width: 25px;
      text-align: center;
      text-decoration: none;
      margin: 5px 2px;
      border-radius: 50%;
    }

    .fa:hover {
      opacity: 0.5;
      text-decoration: none;
    }

    .fa-facebook {
      background: #3B5998;
      color: white;
      margin-top: 30px;
    }

    .fa-whatsapp {
      background: #25d366;
      color: white;
    }

    .fa-twitter {
      background: #55ACEE;
      color: white;
    }

    .fa-instagram {
      background: #125688;
      color: white;
    }

    p {
      text-align: center;

    }





    body {

      padding-left: 240px;
    }
    main {
      position: relative;
      height: 100vh;
    }

    .menu {
      background: #0c5460;
      height: 100vh;
      width: 240px;
      position: fixed;
      top: 0px;
      left: 0;
      z-index: 5;
      outline: none;
    }
    .menu .avatar {
      background: rgba(0, 0, 0, 0.1);
      padding: 2em 0.5em;
      text-align: center;
    }
    .menu .avatar img {
      width: 100px;
      border-radius: 50%;
      overflow: hidden;
      border: 4px solid #ffea92;
      box-shadow: 0 0 0 4px rgba(255, 255, 255, 0.2);
    }
    .menu .avatar h2 {
      font-weight: normal;
      margin-bottom: 0;
    }
    .menu ul {
      list-style: none;
      padding: 0.5em 0;
      margin: 0;
    }
    .menu ul li {
      padding: 0.5em 1em 0.5em 3em;
      font-size: 0.95em;
      font-weight: regular;
      background-repeat: no-repeat;
      background-position: left 15px center;
      background-size: auto 20px;
      transition: all 0.15s linear;
      cursor: pointer;
    }
    .menu ul li.icon-dashboard {
      background-image: url("http://www.entypo.com/images//gauge.svg");
    }
    .menu ul li.icon-customers {
      background-image: url("http://www.entypo.com/images//briefcase.svg");
    }
    .menu ul li.icon-users {
      background-image: url("http://www.entypo.com/images//users.svg");
    }
    .menu ul li.icon-calendar {
      background-image: url("http://www.entypo.com/images//calendar.svg");
    }

    .menu ul li:hover {
      background-color: rgba(0, 0, 0, 0.1);
    }
    .menu ul li:focus {
      outline: none;
    }
    @media screen and (max-width: 900px) and (min-width: 400px) {
      body {
        padding-left: 90px;
      }
      .menu {
        width: 90px;
      }
      .menu .avatar {
        padding: 0.5em;
        position: relative;
      }
      .menu .avatar img {
        width: 60px;
      }
      .menu .avatar h2 {
        opacity: 0;
        position: absolute;
        top: 50%;
        left: 100px;
        margin: 0;
        min-width: 200px;
        border-radius: 4px;
        background: rgba(0, 0, 0, 0.4);
        transform: translate3d(-20px, -50%, 0);
        transition: all 0.15s ease-in-out;
      }
      .menu .avatar:hover h2 {
        opacity: 1;
        transform: translate3d(0px, -50%, 0);
      }
      .menu ul li {
        height: 60px;
        background-position: center center;
        background-size: 30px auto;
        position: relative;
      }
      .menu ul li span {
        opacity: 0;
        position: absolute;
        background: rgba(0, 0, 0, 0.5);
        padding: 0.2em 0.5em;
        border-radius: 4px;
        top: 50%;
        left: 80px;
        transform: translate3d(-15px, -50%, 0);
        transition: all 0.15s ease-in-out;
      }
      .menu ul li span:before {
        content: '';
        width: 0;
        height: 0;
        position: absolute;
        top: 50%;
        left: -5px;
        border-top: 5px solid transparent;
        border-bottom: 5px solid transparent;
        border-right: 5px solid rgba(0, 0, 0, 0.5);
        transform: translateY(-50%);
      }
      .menu ul li:hover span {
        opacity: 1;
        transform: translate3d(0px, -50%, 0);
      }
    }
    @media screen and (max-width: 400px) {
      body {
        padding-left: 0;
      }
      .menu {
        width: 230px;
        box-shadow: 0 0 0 100em rgba(0, 0, 0, 0);
        transform: translate3d(-230px, 0, 0);
        transition: all 0.3s ease-in-out;
      }
      .menu .smartphone-menu-trigger {
        width: 40px;
        height: 40px;
        position: absolute;
        left: 100%;
        background: #5bc995;
      }
      .menu .smartphone-menu-trigger:before,
      .menu .smartphone-menu-trigger:after {
        content: '';
        width: 50%;
        height: 2px;
        background: #fff;
        border-radius: 10px;
        position: absolute;
        top: 45%;
        left: 50%;
        transform: translate3d(-50%, -50%, 0);
      }
      .menu .smartphone-menu-trigger:after {
        top: 55%;
        transform: translate3d(-50%, -50%, 0);
      }
      .menu ul li {
        padding: 1em 1em 1em 3em;
        font-size: 1.2em;
      }
      .menu:focus {
        transform: translate3d(0, 0, 0);
        box-shadow: 0 0 0 100em rgba(0, 0, 0, 0.6);
      }
      .menu:focus .smartphone-menu-trigger {
        pointer-events: none;
      }
    }

  </style>
    {% block style %}
    {% endblock %}
</head>

<body>
  <!-- partial:index.partial.html -->
  <nav class="menu" tabindex="0">
    <div class="smartphone-menu-trigger"></div>
    <header class="avatar">
      <img src="{{ request.user.user_info.profile_picture.url }}" alt="Profile Pic" />
      <br><br>
        <h5 class="font-weight-bold">Manager</h5>
      <h3 class="font-weight-bold"><a href="{% url 'authenticate:profile_url' request.user.id %}">{{ request.user.get_full_name }}</a></h3>
    </header>
    <ul>
      <li tabindex="0" class="icon-dashboard"> <a style="color:white; text-decoration:none;" href="{% url 'authenticate:manager_dashboard_url' request.user.id %}"><span>Dashboard</span></a> </li>
      <li tabindex="0" class="fa fa-sign-out"><a href="{% url 'authenticate:logout_url' %}" style="color:white; text-decoration: none"><span>Logout</span></a></li>
    </ul>
  </nav>
  <main>
    <br><br>
    <!-- content start-->
    {% block content %}
    {% endblock content %}
    <!-- content end-->


    <br><br><br><br><br><br><br>

  </main>
  <!-- partial -->
<script src="{% static 'fa/js/fontawesome.js' %}"></script>
{% block script %}

{% endblock %}
</body>
</html>

templates/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top  ">
    <a class="navbar-brand" href="{% url 'home_url' %}">TravelAid</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
     <span class="navbar-toggler-icon"></span>
   </button>

    <div class="navbar-collapse collapse w-100 order-3 dual-collapse2 ml-auto">

    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'services:accommodation_list_url' %}">Accommodations</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'services:hospital_list_url' %}">Hospitals</a>
        </li>
    </ul>

      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'services:user_appointments_url' request.user.id %}">Appointments</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'services:bookings_url' request.user.id %}">Bookings</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'authenticate:profile_url' request.user.id %}">Profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'authenticate:logout_url' %}">Log Out</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'authenticate:registration_url' %}">Sing Up</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'authenticate:login_url' %}">Log In</a>
        </li>
        {% endif%}
      </ul>
    </div>
</nav>