services/urls.py
from django.urls import path, include
from .views import accommodation_view as accommodation_views
from .views import hospital_view as hospital_views

app_name = 'services'

urlpatterns = [
    path('accommodations/', accommodation_views.AccommodationList.as_view(), name='accommodation_list_url'),
    path('accommodation/<int:pk>/', accommodation_views.AccommodationDetailView.as_view(), name='accommodation_detail_url'),
    path('room/<int:pk>/', accommodation_views.RoomDetailView.as_view(), name='room_details'),
    path('bookings/<int:user_id>/', accommodation_views.BookingsView.as_view(), name='bookings_url'),
    path('edit_booking/<int:booking_id>/', accommodation_views.BookingsView.as_view(), name='edit_booking_url'),
    path('print_invoice/<int:booking_id>/', accommodation_views.DownloadInvoice.as_view(), name='print_invoice_url'),
    path('make_accommodation_payment/<int:booking_id>/', accommodation_views.AccommodationPaymentView.as_view(), name='make_accommodation_payment_url'),
    path('delete_booking/<int:booking_id>/', accommodation_views.BookingDeleteView.as_view(), name='delete_booking_url'),


    path('hospitals/', hospital_views.HospitalList.as_view(), name='hospital_list_url'),
    path('hospital/<int:id>/', hospital_views.HospitalDetailsView.as_view(), name='hospital_details_url'),
    path('hospital/doctor/<int:doctor_id>', hospital_views.DoctorDetailsView.as_view(), name='doctor_details_url'),
    path('request_appointments/<int:doctor_id>/', hospital_views.DoctorDetailsView.as_view(), name='request_appointments_url'),
    path('my_appointments/<int:user_id>/', hospital_views.UserAppointmentView.as_view(), name='user_appointments_url'),
    path('edit_appointment/<int:appointment_id>/', hospital_views.UserAppointmentView.as_view(), name='edit_appointment_url'),
    path('delete_appointment/<int:appointment_id>/', hospital_views.DeleteAppointmentView.as_view(), name='delete_appointment_url'),

    # Doctor Controls
    path('manage-appointments/<int:doctor_id>/', hospital_views.ManageAppointmentsView.as_view(), name='manage_appointments_url'),
    path('approve-appointment/<int:approve_id>/', hospital_views.ManageAppointmentsView.as_view(), name='approve_appointmetn_url'),
    path('reject-appointment/<int:reject_id>/', hospital_views.ManageAppointmentsView.as_view(), name='reject_appointment_url'),
    path('release-appointment/<int:release_id>/', hospital_views.ManageAppointmentsView.as_view(), name='release_appointment_url'),
    path('download-appointment-invoice/<int:appointment_bill_id>/', hospital_views.DownloadAppointmentInvoice.as_view(), name='download_appointment_invoice'),
]

system/urls.py
from django.urls import path

urlpatterns = [

]

travel_aid/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users_auth.views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name='home_url'),
    path('admin/', admin.site.urls),
    path('auth/', include('users_auth.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('address/', include('address.urls')),
    path('service/', include('services.urls')),
    path('system/', include('system.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users_auth/urls.py
from django.urls import path, include
from . import views

app_name = 'authenticate'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login_url'),
    path('logout/', views.LogoutView.as_view(), name='logout_url'),
    path('profile/<int:pk>/', views.ProfileView.as_view(), name='profile_url'),
    path('register/', views.RegistrationView.as_view(), name='registration_url'),
    path('admin_dashboard/', views.AdminDashboardView.as_view(), name='admin_dashboard_url'),
    path('doctor_dashboard/<int:doctor_id>/', views.DoctorDashboardView.as_view(), name='doctor_dashboard_url'),
    path('police_dashboard/', views.PoliceDashboardView.as_view(), name='police_dashboard_url'),
    path('manager_dashboard/<int:manager_id>/', views.ManagerDashboardView.as_view(), name='manager_dashboard_url'),

    # Manager's Control
    path('add-accommodation/', views.AccommodationManageView.as_view(), name='add_accommodation'),
    path('edit-accommodation/<int:editable_id>',  views.AccommodationManageView.as_view(), name='edit_accommodation'),
    path('delete-accommodation/<int:deletable_id>', views.AccommodationManageView.as_view(), name='delete_accommodation'),

    path('add-room/', views.RoomManageView.as_view(), name='add_room_url'),
    path('edit-room/<int:editable_id>', views.RoomManageView.as_view(), name='edit_room_url'),
    path('delete-room/<int:deletable_id>', views.RoomManageView.as_view(), name='delete_room_url'),

    path('manage-booking-request/<int:manager_id>', views.ManageBookingRequestView.as_view(), name='manage_booking_request'),
    path('approve-booking-request/<int:approvable_id>', views.ManageBookingRequestView.as_view(), name='approve_booking_request'),
    path('reject-booking-request/<int:rejectable_id>', views.ManageBookingRequestView.as_view(), name='reject_booking_request'),

    # managing user message
    path('send-message/', views.ManageUserMessage.as_view(), name='send_message')
]

services/models/accommodation_models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from address.models import Address
# Create your models here.
from users_auth.models import APPROVE_USER_STATUS, User

AVAILABLE = 1
PENDING = 2
BOOKED = 3

AC = 1
Non_AC = 2

BKASH = 1
ROCKET = 2

ROOM_STATUS_CHOICES = (
    (AVAILABLE, "Available"),
    (PENDING, "Pending"),
    (BOOKED, "Booked")
)

ROOM_TYPE_CHOICES = (
    ('AC', 'AC'),
    ('Non AC', 'Non AC')
)

PAYMENT_PROVIDERS = (
    (BKASH, "bKash"),
    (ROCKET, "Rocket"),
)

PAYMENT_STATUS_CHOICES = (
    ('Paid', 'Paid'),
    ('Unpaid', 'Unpaid'),
    ('Partially Paid', 'Partially Paid'),
    ('Over Paid', 'Over Paid'),
)


class Accommodation(models.Model):
    name = models.CharField(max_length=200)
    owner = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='home_owner', null=True, blank=True)
    image = models.ImageField(upload_to='accommodations', null=True, blank=True)
    address = models.ForeignKey(Address, on_delete=models.DO_NOTHING, related_name='accommodation_address' , null=True, blank=True)
    description = RichTextUploadingField(null=True, blank=True)

    def __str__(self):
        return self.name


class Room(models.Model):
    accommodation = models.ForeignKey(Accommodation, on_delete=models.SET_NULL, null=True, blank=True)
    room_number = models.CharField(max_length=100)
    image = models.ImageField(upload_to='rooms', null=True, blank=True)
    description = RichTextUploadingField(null=True, blank=True)
    cost_per_day = models.FloatField(default=0)
    room_type = models.CharField(choices=ROOM_TYPE_CHOICES, default='Non AC', max_length=20)
    current_status = models.IntegerField(choices=ROOM_STATUS_CHOICES, default=1)

    def __str__(self):
        return "{a} -> {b}".format(a=self.room_number, b=self.accommodation.name)


class BookAccommodation(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='book_user', null=True, blank=True)
    room = models.ForeignKey(Room, on_delete=models.SET_NULL, related_name='book_room', null=True, blank=True)
    start_date = models.DateField()
    end_date = models.DateField()
    requested_date = models.DateTimeField(auto_now_add=True)
    total_bills = models.FloatField()
    paid_bills = models.FloatField(default=0)
    due_bills = models.FloatField(default=0)
    payment_status = models.CharField(choices=PAYMENT_STATUS_CHOICES, default="Unpaid", max_length=20)
    status = models.IntegerField(choices=APPROVE_USER_STATUS, default=1)
    user_note = models.TextField(null=True, blank=True)
    manager_note = models.TextField(null=True, blank=True)

    def __str__(self):
        return "{a} by {b} ".format(a=self.room.room_number, b=self.user.first_name)


class AccommodationBillPayment(models.Model):
    bill = models.ForeignKey(BookAccommodation, on_delete=models.SET_NULL, related_name='bill', null=True, blank=True)
    payment_bdt = models.FloatField()
    payment_provider = models.IntegerField(choices=PAYMENT_PROVIDERS, default=1)
    account_number = models.CharField(max_length=11, null=True, blank=True)
    transaction_id = models.CharField(max_length=20, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    note = models.TextField(null=True, blank=True)
    proof = models.FileField(upload_to='payments/', null=True, blank=True)

    def __str__(self):
        return "Bill of - {a}".format(a=self.bill.room.room_number)

services/views/accommodation_view.py
import datetime

from django.contrib import messages
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from address.models import District, Address
from services.models.accommodation_models import Accommodation, Room, BookAccommodation, AccommodationBillPayment
from utils.filter import filter_by_address, filter_room
from utils.print_invoice import render_to_pdf
from django.contrib.auth.mixins import LoginRequiredMixin


class AccommodationList(LoginRequiredMixin, View):
    def get(self, request):
        districts = District.objects.all()
        accommodations = Accommodation.objects.all()
        context = {
            'districts': districts,
            'accommodations': accommodations,
        }
        return render(request, 'services/accommodation/list.html', context)

    def post(self, request):
        data = request.POST
        location = data.get('location')
        district = data.get('district')
        zip_code = data.get('zip_code')

        districts = District.objects.all()
        accommodations = filter_by_address(Accommodation, location, district, zip_code)

        context = {
            'districts': districts,
            'accommodations': accommodations,
        }
        return render(request, 'services/accommodation/list.html', context)


class AccommodationDetailView(LoginRequiredMixin, View):
    def get(self, request, pk):
        accommodation_obj = get_object_or_404(Accommodation, pk=pk)
        all_room = accommodation_obj.room_set.all()
        rooms = accommodation_obj.room_set.all()
        available_rooms_count = accommodation_obj.room_set.filter(current_status=1).count()
        booked_rooms_count = accommodation_obj.room_set.filter(current_status=3).count()
        context = {
            'all_room': all_room,
            'object': accommodation_obj,
            'rooms': rooms,
            'available_rooms': available_rooms_count,
            'booked_rooms': booked_rooms_count,
        }
        return render(request, 'services/accommodation/details.html', context)

    def post(self, request, pk):
        accommodation_obj = get_object_or_404(Accommodation, pk=pk)
        all_room = accommodation_obj.room_set.all()
        available_rooms_count = accommodation_obj.room_set.filter(current_status=1).count()
        booked_rooms_count = accommodation_obj.room_set.filter(current_status=3).count()

        room_status = request.POST.get('room_status')
        room_type = request.POST.get('room_type')
        cost_per_day = request.POST.get('cost_per_day')

        rooms = filter_room(all_room, room_status, room_type, cost_per_day)

        context = {
            'all_room': all_room,
            'object': accommodation_obj,
            'rooms': rooms,
            'available_rooms': available_rooms_count,
            'booked_rooms': booked_rooms_count,
        }
        return render(request, 'services/accommodation/details.html', context)


class RoomDetailView(LoginRequiredMixin, View):
    def get(self, request, pk):
        room_obj = get_object_or_404(Room, pk=pk)
        context = {
            'room': room_obj,
        }
        return render(request, 'services/accommodation/room_details.html', context)

    def post(self, request, pk):
        room_obj = get_object_or_404(Room, pk=pk)
        from_date = request.POST.get('from_date')  # Jan 9, 2021 [format specified in JS using datepicker ]
        from_date = datetime.datetime.strptime(from_date, '%b %d, %Y').strftime('%Y-%m-%d')  # 2021-01-09
        to_date = request.POST.get('to_date')
        to_date = datetime.datetime.strptime(to_date, '%b %d, %Y').strftime('%Y-%m-%d')  # 2021-01-09
        total_bills = request.POST.get('total_bills')
        note = request.POST.get('note')

        book_accommodation = BookAccommodation(user=request.user, room=room_obj, start_date=from_date, end_date=to_date,
                                               total_bills=total_bills, due_bills=total_bills, user_note=note)
        book_accommodation.save()
        messages.success(request, 'Booking Request Submitted Successfully. ')
        return redirect('services:bookings_url', user_id=request.user.id)


class BookingsView(LoginRequiredMixin, View):
    def get(self, request, user_id):
        bookings = BookAccommodation.objects.filter(user=request.user)
        context = {
            'bookings': bookings,
        }
        return render(request, 'services/accommodation/bookings.html', context)

    def post(self, request, booking_id):
        booking_obj = get_object_or_404(BookAccommodation, pk=booking_id)

        data = request.POST
        from_date = data.get('from_date')
        from_date = datetime.datetime.strptime(from_date, '%b %d, %Y').strftime('%Y-%m-%d')  # 2021-01-09
        to_date = data.get('to_date')
        to_date = datetime.datetime.strptime(to_date, '%b %d, %Y').strftime('%Y-%m-%d')  # 2021-01-09
        total_bills = data.get('total_bills')
        note = data.get('note')

        booking_obj.start_date = from_date
        booking_obj.end_date = to_date
        booking_obj.total_bills = total_bills
        booking_obj.note = note
        booking_obj.save()
        messages.success(request, 'Booking Information Updated Successfully. ')

        return redirect('services:bookings_url', user_id=booking_obj.user.id)


class DownloadInvoice(LoginRequiredMixin,View):
    def get(self, request, booking_id, *args, **kwargs):
        invoice_obj = get_object_or_404(BookAccommodation, pk=booking_id)

        context = {
            'invoice_obj': invoice_obj,
        }

        pdf = render_to_pdf('services/accommodation/pdf_template.html', context)

        response = HttpResponse(pdf, content_type='application/pdf')
        filename = "Invoice_%s.pdf" % (invoice_obj.id)
        content = "attachment; filename='%s'" % (filename)
        response['Content-Disposition'] = content
        return response


class AccommodationPaymentView(LoginRequiredMixin, View):
    def post(self, request, booking_id):
        data = request.POST
        booking_id = data.get('booking_id')
        bill_obj = get_object_or_404(BookAccommodation, pk=int(booking_id))
        payment_method = data.get('payment_method')
        account_number = data.get('account_number')
        payment_bdt = data.get('payment_bdt')
        tx_id = data.get('tx_id')
        proof = request.FILES.get('proof')
        note = data.get('note')

        accommodation_bill = AccommodationBillPayment(bill=bill_obj, payment_bdt=payment_bdt, transaction_id=tx_id,
                                                      payment_provider=payment_method, account_number=account_number,
                                                      proof=proof, note=note)
        accommodation_bill.save()
        messages.success(request, 'BDT {a} Payment Successful. '.format(a=payment_bdt))

        bill_obj.paid_bills += float(payment_bdt)
        bill_obj.due_bills = bill_obj.total_bills - bill_obj.paid_bills

        if bill_obj.total_bills == bill_obj.paid_bills:
            bill_obj.payment_status = 'Paid'
        elif 0 < bill_obj.due_bills < bill_obj.total_bills:
            bill_obj.payment_status = 'Partially Paid'
        elif bill_obj.due_bills == bill_obj.total_bills:
            bill_obj.payment_status = 'Unpaid'
        else:
            bill_obj.payment_status = 'Over Paid'
        bill_obj.save()
        return redirect('services:bookings_url', user_id=bill_obj.user.id)


class BookingDeleteView(LoginRequiredMixin, View):
    def get(self, request, booking_id):
        booking_obj = get_object_or_404(BookAccommodation, pk=booking_id)
        user = booking_obj.user
        messages.success(request, 'Booking Deleted Successfully. ')
        booking_obj.delete()
        return redirect('services:bookings_url', user_id=user.id)

templates/services/accommodation/bookings.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    {% include 'navbar.html' %}
    <div class="container">
        {% if messages  %}
              {% for message in messages  %}
                <h5 class="font-weight-bold text-center alert alert-{{message.tags}}"> {{message}} </h5>
              {% endfor %}
        {% endif %}

        <div class="jumbotron">
            {% if bookings.count == 0 %}
                <h2 class="text-center">You haven't book any Room. Please, <a href="{% url 'services:accommodation_list_url' %}">Book One</a></h2>
            {% else %}
                <h2 class="text-center">Your All Bookings. </h2>
            {% endif %}
        </div>

    {% if bookings.count != 0 %}
    
        <div id="table">
            <table class="table table-stripped">
                  <thead>
                    <tr>
                      <th scope="col">#</th>
                      <th scope="col">Cottage</th>
                      <th scope="col">Room Number</th>
                      <th scope="col">Starting Date</th>
                      <th scope="col">Ending Date</th>
                      <th scope="col">Total Costs(BDT)</th>
                      <th scope="col">Paid(BDT)</th>
                      <th scope="col">Status</th>
                      <th scope="col" class="text-center">Action</th>
                    </tr>

                  </thead>
                  <tbody>


                {% for booking in bookings %}
                  <tr>
                    <td>{{ forloop.counter }}</td>
                    <td><a href="{% url 'services:accommodation_detail_url' booking.room.accommodation.id %}">{{ booking.room.accommodation.name }}</a></td>
                    <td><a href="{% url 'services:room_details' booking.room.id %}">{{ booking.room.room_number }}</a></td>
                    <td>{{ booking.start_date| date:"b d, Y"}}</td>
                    <td>{{ booking.end_date | date:"b d, Y" }}</td>
                    <td>{{ booking.total_bills}}</td>
                    <td>{{ booking.paid_bills}}</td>
                    <td>{{ booking.get_status_display }}</td>
                    <td>
                        {% if booking.paid_bills < booking.total_bills %}
                            <button data-toggle="modal" data-target="#payment{{ booking.id }}" class="btn btn-success"><i class="fa fa-money"></i></button>
                            {% include 'modals/payment_modal.html' %}
                        {% endif %}
                            <button data-toggle="modal" data-target="#paymentHistory{{ booking.id }}" class="btn btn-secondary"><i class="fa fa-history"></i></button>
                            {% include 'modals/payment_history.html' %}
                        {% if booking.status == 2 %}
                            <a href="{% url 'services:print_invoice_url' booking.id %}" class="btn btn-success"><i class="fa fa-print"></i></a>
                        {% endif %}
                        <button data-toggle="modal" data-target="#bookingDetails{{ booking.id }}" class="btn btn-primary"><i class="fa fa-eye"></i></button>
                            {% include 'modals/view_booking_details.html' %}
                        {% if booking.status == 1 %}
                        <button data-toggle="modal" data-target="#delete_booking{{ booking.id }}" class="btn btn-danger"><i class="fa fa-trash"></i></button>
                            {% include 'modals/booking_delete.html' %}
                       {% endif %}
                    </td>
                  </tr>

                {% endfor %}
              </tbody>
              </table>
        </div>
        {% endif %}

    </div>




{% endblock content %}

{% block script %}

    <script>
    function  calculate_days(){
        let start= $("#from_date").datepicker("getDate");
        let end= $("#to_date").datepicker("getDate");
        let days = (end- start) / (1000 * 60 * 60 * 24);
        if(days < 0){
            return "Invalid"
        }
        else{
            return days
        }
    }
    </script>

    <script>
        $(document).ready(function (){

            $("#payment_bdt").on('keyup', function (){
                let amount = Number($("#payment_bdt").val())
                console.log(amount)
                if(amount < 0 || isNaN(amount)){
                    $("#error_msg").text("Amount Must Be Positive Number. ");
                    $("#payment_bdt").css('border', '1px solid red');
                    $("#payment_btn").hide()
                }
                else{
                    $("#error_msg").text('');
                    $("#payment_bdt").css('border', 'yellow')
                    $("#payment_btn").show()
                }

            })

            $("#from_date").datepicker({
                onSelect:function (){
                    let date = $("#from_date").datepicker('getDate')
                    let today = new Date()
                    today.setHours(0,0,0,0);
                    if(date < today){
                      $("#error_msg").text('You can\'t book from earlier than today. ')
                      $("#to_date_div").hide()
                      $("#update_btn").hide()
                    }
                    else{
                      $("#to_date_div").show()
                      $("#error_msg").text('')
                      $("#update_btn").show()
                    }
                    let days = calculate_days()
                    if(days != 'Invalid'){
                      $("#error_msg2").text('')
                      $("#update_btn").show()
                      let cpd = $("#cost_per_day").val()
                      let total_bills = Number(cpd) * (days+1)
                      $("#total_bills").val(total_bills)
                      }
                      else{
                          $("#error_msg2").text('End Date Must be greater than Start Date')
                          $("#update_btn").hide()
                      }
                },
                dateFormat: "M d, yy",
                changeMonth: true,
                changeYear: true,

            })

            $("#to_date").datepicker({
                dateFormat: "M d, yy",
                changeMonth: true,
                changeYear: true,
                onSelect: function () {
                  let days = calculate_days()
                  if(days != 'Invalid'){
                      $("#error_msg2").text('')
                      $("#update_btn").show()
                      let cpd = $("#cost_per_day").val()
                      let total_bills = Number(cpd) * (days+1)
                      $("#total_bills").val(total_bills)
                  }
                  else{
                      $("#error_msg2").text('End Date Must be greater than Start Date')
                      $("#update_btn").hide()
                  }
                }
            })

        })
    </script>
{% endblock script %}

templates/services/accommodation/details.html
{% extends 'base.html' %}

{% block style %}

    <style>
        body{
            background: #fcf8e3;
        }
    </style>

{% endblock %}
{% block content %}
    {% if request.user.is_user %}
        {% include 'navbar.html' %}
    {% else %}
        <div class="row text-center font-weight-bold bg-dark">
                <div class="col-md-4">
                    {% if request.user.is_doctor %}
                         <a class="nav-link" href="{% url 'authenticate:doctor_dashboard_url' request.user.id %}">Dashboard</a>
                    {% endif %}
                    {% if request.user.is_manager %}
                        <a class="nav-link" href="{% url 'authenticate:manager_dashboard_url' request.user.id %}">Dashboard</a>
                    {% endif %}
                </div>
          </div>
    {% endif %}


    <div class="container my-4">
         <h3 class="text-center" style="font-weight: bold"> Details of : {{ object.name }} </h3>

         <div id="image" class="my-3">
             <img class="img-fluid" src="{{ object.image.url }}" alt="Image Not Available.">
         </div>

        <div class="my-3">
            <section id="rooms_info" class="mt-5">

                <h3 class="text-center" style="font-weight: bold">Rooms Information</h3>

                <div class="row" style="margin-left: 120px;">
                    <div class="col-md-3" style="height: 100px; width: 70px; background: #1c7430">
                        <h2 class="text-center">Total Rooms</h2>
                        <h3 class="text-center">{{ all_room.count }}</h3>
                    </div>
                    <div class="col-md-3 mx-5" style="height: 100px; width: 70px; background: #0c5460">
                        <h2 class="text-center">Available</h2>
                        <h3 class="text-center">{{ available_rooms }}</h3>
                    </div>
                    <div class="col-md-3" style="height: 100px; width: 70px; background: #366769">
                        <h2 class="text-center">Booked</h2>
                        <h3 class="text-center">{{ booked_rooms }}</h3>
                    </div>
                </div>
            </section>

            <section id="filter_room" class="my-5">

                <h3 class="text-center" style="font-weight: bold">Filter Rooms</h3>

                <form method='post' action=""> {% csrf_token %}
                    <div class="row">
                        <div class="col-md-4">
                            <select id='room_status' name='room_status' class="form-control">
                                <option value='' selected>Select Status</option>
                                <option value="1">Available</option>
                                <option value="3">Booked</option>
                            </select>
                        </div>
                        <div class="col-md-4">
                            <select id='room_type' name='room_type' class="form-control">
                                <option value='' selected>Select Type</option>
                                <option value="AC">AC</option>
                                <option value="Non AC">Non AC</option>
                            </select>
                        </div>
                        <div class="col-md-2">
                            <input type="text" name="cost_per_day" placeholder="Max Cost/Day" id="zip_code" class="form-control">
                        </div>
                        <div class="col-md-2">
                            <input type="submit" class="btn btn-light text-dark" id="search_submit">
                        </div>
                    </div>

                </form>
            </section>

            <section id="room_list" class="my-5">
                {% if rooms.count == 0 %}
                    <div class="jumbotron">
                        No Rooms Found!!
                    </div>
                {% endif %}
                <div class="row mt-3">
                   {% for room in rooms %}
                       <div class="col-lg-4">
                        <div class="card" style="background: #f7f7f7">
                            <div class="card-header">
                                <h5 class="text-center" style="font-weight: bold">{{ room.room_number }}</h5>
                                <h6 class="text-center" style="font-weight: bold">{{ room.room_type }} | {{ room.cost_per_day }} BDT/Day</h6>
                            </div>
                            <div class="card-body">
                                <img style="height: 180px; width: 600px" src="{{ room.image.url }}" alt="Image Not Available" class="img-fluid">
                            </div>
                            <div class="card-footer">
                                <a href="{% url 'services:room_details' room.id %}" type="button" class="btn btn-primary btn-block">View Details</a>
                            </div>
                        </div>
                    </div>
                   {% endfor %}
                </div>
            </section>


            <section id="accommodation_description" class="my-5">
                <h3 class="text-center" style="font-weight: bold">Description</h3>
                <div class="row">
                    <div class="col-md-12">
                        {{ object.description | safe }}
                    </div>

                </div>
            </section>

        </div>

    </div>


{% endblock content %}

{% block script %}
    <script>
        document.addEventListener("DOMContentLoaded", function (event) {
            var scrollpos = sessionStorage.getItem('scrollpos');
            if (scrollpos) {
                window.scrollTo(0, scrollpos);
                sessionStorage.removeItem('scrollpos');
            }
        });

        window.addEventListener("beforeunload", function (e) {
            sessionStorage.setItem('scrollpos', window.scrollY);
        });

        $(window).blur(function(){
            sessionStorage.clear();
        });
    </script>
{% endblock script %}